# all name and description attributes are not required
connections:
  web:
    # full attributes edition
    - connection:
        name: ASF homepage
        #(required) the url you want to check if it is accessible
        url: http://www.apache.org/
        description: The Apache Software Foundation website
    # simplest attributes edition
    - connection:
        url: https://mvnrepository.com/
    - connection:
        name: unreachable site
        url: https://www.unreachable.com

  ports:
    # full attributes edition
    - connection:
        name: mysql
        #(required)
        host: nanmatou.club
        #(required)
        port: 3306
        description: mysql port
    # simplest attributes edition
    - connection:
        host: nanmatou.club
        port: 3319
